from . import np_area
from . import np_region
from . import np_warehouse_type
from . import np_settlement
from . import np_warehouse
from . import np_street
from . import res_partner
from . import plugit_novaposhta_ttn
from . import plugit_novaposhta_ttn_seats
from . import delivery_carrier
from . import stock_picking
from . import ir_cron
